# Generated by Django 4.0.2 on 2022-02-26 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MantraAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200, unique=True)),
                ('artist', models.CharField(max_length=200, unique=True)),
                ('album_cover_image', models.FileField(blank=True, null=True, upload_to='mantra_album_cover_image/')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MantraLyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mantra_lyric_image', models.FileField(blank=True, null=True, upload_to='mantra_lyrics_image/')),
                ('mantra_name', models.CharField(default=' ', max_length=40)),
                ('artist', models.CharField(default=' ', max_length=40)),
                ('lyrics', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mantra_Lyrics_fk', to='mantras.mantraalbum')),
            ],
        ),
        migrations.CreateModel(
            name='Mantra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mantra_image', models.FileField(blank=True, null=True, upload_to='mantra_image/')),
                ('mantra_name', models.CharField(default=' ', max_length=40)),
                ('artist', models.CharField(default=' ', max_length=40)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='mantra_mp3/')),
                ('mantra_url', models.CharField(default=' ', max_length=200)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Albums_mantra_fk', to='mantras.mantraalbum')),
            ],
        ),
    ]
