# Generated by Django 4.0.2 on 2022-03-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantra',
            name='crawl_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mantra',
            name='firebase_url',
            field=models.CharField(default=' ', max_length=2000),
        ),
        migrations.AlterField(
            model_name='mantra',
            name='mantra_url',
            field=models.CharField(default=' ', max_length=2000),
        ),
    ]
