# Generated by Django 4.0.2 on 2022-03-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoroscopeUsersLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_key', models.CharField(default=' ', max_length=16)),
                ('day', models.CharField(default=' ', max_length=16)),
                ('sign', models.CharField(default=' ', max_length=16)),
                ('language', models.CharField(default=' ', max_length=16)),
                ('timezone', models.DateField(auto_now_add=True)),
                ('out_message', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
