# Generated by Django 4.0.2 on 2022-02-26 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200, unique=True)),
                ('artist', models.CharField(max_length=200, unique=True)),
                ('album_cover_image', models.FileField(upload_to='album_cover_image/')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_image', models.FileField(upload_to='song_image/')),
                ('song_name', models.CharField(default=' ', max_length=40)),
                ('artist', models.CharField(default=' ', max_length=40)),
                ('media_file', models.FileField(upload_to='songs_mp3/')),
                ('song_url', models.CharField(default=' ', max_length=200)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Albums_songs_fk', to='songs.albums')),
            ],
        ),
        migrations.CreateModel(
            name='SongLyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_lyric_image', models.FileField(upload_to='song_image/')),
                ('song_name', models.CharField(default=' ', max_length=40)),
                ('artist', models.CharField(default=' ', max_length=40)),
                ('lyrics', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Song_Lyrics_fk', to='songs.albums')),
            ],
        ),
    ]
