# Generated by Django 4.0.2 on 2022-02-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='album_cover_image',
            field=models.FileField(blank=True, null=True, upload_to='album_cover_image/'),
        ),
        migrations.AlterField(
            model_name='songlyrics',
            name='song_lyric_image',
            field=models.FileField(blank=True, null=True, upload_to='song_image/'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='songs_mp3/'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='song_image',
            field=models.FileField(blank=True, null=True, upload_to='song_image/'),
        ),
    ]
