# Generated by Django 4.0.2 on 2022-03-08 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_songs_crawl_required_songs_firebase_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LyricsAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200, unique=True)),
                ('artist', models.CharField(max_length=200, unique=True)),
                ('album_cover_image', models.FileField(blank=True, null=True, upload_to='lyric_album_cover_image/')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='songlyrics',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Song_Lyrics_fk', to='songs.lyricsalbum'),
        ),
    ]
