# Generated by Django 4.0.2 on 2022-02-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(default=' ', max_length=100)),
                ('parameter_value', models.CharField(default=' ', max_length=100)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_key', models.CharField(default=' ', max_length=16)),
                ('mapped_key', models.CharField(default=' ', max_length=16)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
