# Generated by Django 4.0.2 on 2022-03-10 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_deviceloginlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=' ', max_length=100)),
                ('feedback_message', models.TextField()),
                ('mobile', models.CharField(default=' ', max_length=100)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_feedback_log', to='authentication.deviceauth')),
            ],
        ),
    ]
